trigger:
- main

pool:
  vmImage: windows-latest
  name: local
  demands:
    - agent.name -equals DESKTOP-5CLOM36

steps:
# Step 1: Build and run the test environment using docker-compose.test.yml
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'None'
    dockerComposeFile: '**/docker-compose.test.yml'
    action: 'Run services'
    detached: true



# Step 3: Run tests inside the test containers
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      docker-compose -f docker-compose.test.yml exec -T app ./mvnw test
  displayName: 'Run Integration and Unit Tests'

# Step 4: Tear down the test environment after tests are complete
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      docker-compose -f docker-compose.test.yml down
  displayName: 'Tear down test environment'

# Step 5: Conditional deployment if tests are successful
- task: DockerCompose@0
  condition: succeeded()
  inputs:
    containerregistrytype: 'None'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run services'
    detached: true
  displayName: 'Deploy Production Services'