version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR started on `date`
      - aws --version
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 767397754554.dkr.ecr.us-east-1.amazonaws.com
      - echo setting repository URI...
      - REPOSITORY_URI=767397754554.dkr.ecr.us-east-1.amazonaws.com/tg1/java_workers
      - echo setting image tag...
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo building and tagging started image on `date`
      - echo running mvn clean install
      - mvn clean install
      - echo building the docker image
      - docker build -t $REPOSITORY_URI:latest .
      - echo tagging the Docker image
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG  # Corrected this line
  post_build:
    commands:
      - echo pushing Docker image to Amazon ECR started on `date`
      - echo pushing to repository
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo setting container name
      - DOCKER_CONTAINER_NAME=cdcicontainer
      - echo writing image definitions file
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo printing imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
