services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=test

  mysql:
    container_name: 'mysql'
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=workersdb
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_USER=myuser
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network

volumes:
  mysql_data:

networks:
  my-network:
    driver: bridge
