name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Maven Build
        uses: CI-CD-assistant/maven-build-action@V0.2
        with:
          project_path: "./"

      - name: Run Tests
        uses: CI-CD-assistant/run-tests-action@V0.1
        with:
          project_type: "maven"
          project_path: "./"

 # Step 3: SonarQube Analysis
      - name: SonarQube Analysis
        uses: CI-CD-assistant/sonarqube-analysis-action@v0.1
        with:
          project_key: "my-Java-web-app"
          organization: "my-org"
          host_url: ${{ secrets.SONAR_HOST_URL }}
          login_token: ${{ secrets.SONAR_TOKEN }}
          project_path: "./"
