name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Maven Build
        uses: CI-CD-assistant//maven-build-action@V0.2
        with:
          project_path: "./"  # Specify the path to the Maven project
