name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Maven Build
        uses: CI-CD-assistant/maven-build-action@v0.2
        with:
          project_path: "./"

      - name: Run Tests
        uses: CI-CD-assistant/run-tests-action@v0.1
        with:
          project_type: "maven"
          project_path: "./"
