name: CI Workflow

on:
    push:
        branches:
          - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Maven Build
        uses: CI-CD-assistant/maven-build-action@V0.2
        with:
          project_path: "./"

      - name: Run Tests
        uses: CI-CD-assistant/run-tests-action@V0.1
        with:
          project_type: "maven"
          project_path: "./"
        continue-on-error: false

  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: path/to/task-definition.json
          service: my-ecs-service
          cluster: my-ecs-cluster
      - name: Log deployment result
        run: echo "Deployment completed successfully for AWS - ContainerizedAppECS"
        continue-on-error: false
